reproduce NotImplementedError: ibf_dump_object_unsupported
bundle exec rake test:hoge

expected
```
> hoge
```

but

```
rake aborted!
NotImplementedError: ibf_dump_object_unsupported: 0x00007f3981832428 [3LM R  ] T_ICLASS
/home/st6446/workspace/temp_rails_app/config/application.rb:7:in `<top (required)>'
/home/st6446/workspace/temp_rails_app/Rakefile:4:in `require_relative'
/home/st6446/workspace/temp_rails_app/Rakefile:4:in `<top (required)>'
/home/st6446/.rbenv/versions/3.1.2/bin/bundle:25:in `load'
/home/st6446/.rbenv/versions/3.1.2/bin/bundle:25:in `<main>'
(See full trace by running task with --trace)
```